[package]
name = "aa-battles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
reqwest = "0.11.18"
sea-orm = { version = "0.11.3",  features = [
    "debug-print",
    "runtime-tokio-native-tls",
    "sqlx-postgres",
]}
serde = "1.0.164"
serde_json = "1.0.99"
tokio = { version = "1.29.1", features = ["full"] }
