[package]
name = "aa-battles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
mockall = "0.11.4"
rand = "0.8.5"
reqwest = { version="0.11.18", features =  ["json"] }
serde = { version ="1.0.164", features = ["derive"] }
serde-this-or-that = "0.4.2"
serde_json = "1.0.99"
tokio = { version = "1.29.1", features = ["full"] }
