use std::collections::HashMap;

use crate::{
    service::query::{ArmorType, Army, ArmyName, WeaponType},
    util::create_hash_of_defaults,
};

pub fn get_mock_defaults() -> HashMap<ArmyName, Army> {
    let mut vec_of_mock_defaults = vec![
        Army {
            id: 1,
            name: ArmyName::PeacekeeperMonks,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 5,
            attack_speed: 1,
            accuracy: 1.0,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Blunt,
            armor_type: ArmorType::Unarmored,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 2,
            name: ArmyName::ImperialLegionnaires,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.75,
            flying: false,
            range: 10,
            attack_speed: 1,
            accuracy: 1.0,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Edged,
            armor_type: ArmorType::Plate,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 3,
            name: ArmyName::NorthWatchLongbowmen,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 150,
            attack_speed: 1,
            accuracy: 0.75,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Piercing,
            armor_type: ArmorType::Unarmored,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 4,
            name: ArmyName::HighbornCavalry,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.5,
            flying: false,
            range: 10,
            attack_speed: 2,
            accuracy: 0.9,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Edged,
            armor_type: ArmorType::Plate,
            agility: 0.25,
            speed: 10,
        },
        Army {
            id: 5,
            name: ArmyName::RoninImmortals,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 5,
            attack_speed: 2,
            accuracy: 1.0,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Edged,
            armor_type: ArmorType::Chain,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 6,
            name: ArmyName::ShinobiMartialArtists,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 5,
            attack_speed: 3,
            accuracy: 1.0,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Blunt,
            armor_type: ArmorType::Leather,
            agility: 0.5,
            speed: 5,
        },
        Army {
            id: 7,
            name: ArmyName::AmazonianHuntresses,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 5,
            attack_speed: 1,
            accuracy: 1.0,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Piercing,
            armor_type: ArmorType::Leather,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 8,
            name: ArmyName::AvianCliffDwellers,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.26,
            flying: true,
            range: 10,
            attack_speed: 1,
            accuracy: 0.9,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Edged,
            armor_type: ArmorType::Leather,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 9,
            name: ArmyName::MagiEnforcers,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 15,
            attack_speed: 1,
            accuracy: 1.0,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Magic,
            armor_type: ArmorType::Chain,
            agility: 0.1,
            speed: 5,
        },
        Army {
            id: 10,
            name: ArmyName::SkullClanDeathCultists,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 100,
            attack_speed: 1,
            accuracy: 0.75,
            aoe: 3.00,
            spread: 1.00,
            weapon_type: WeaponType::Magic,
            armor_type: ArmorType::Unarmored,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 11,
            name: ArmyName::BarbariansOfTheOuterSteppe,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 100,
            attack_speed: 1,
            accuracy: 0.75,
            aoe: 0.00,
            spread: 2.00,
            weapon_type: WeaponType::Crushing,
            armor_type: ArmorType::Chain,
            agility: 0.25,
            speed: 10,
        },
        Army {
            id: 12,
            name: ArmyName::OathSwornKnights,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.5,
            flying: false,
            range: 5,
            attack_speed: 1,
            accuracy: 0.75,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Edged,
            armor_type: ArmorType::Plate,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 13,
            name: ArmyName::Militia,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 5,
            attack_speed: 1,
            accuracy: 0.75,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Edged,
            armor_type: ArmorType::Unarmored,
            agility: 0.25,
            speed: 5,
        },
        Army {
            id: 14,
            name: ArmyName::HoodedAssassins,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 10,
            attack_speed: 3,
            accuracy: 1.0,
            aoe: 0.00,
            spread: 3.00,
            weapon_type: WeaponType::Edged,
            armor_type: ArmorType::Unarmored,
            agility: 0.35,
            speed: 10,
        },
        Army {
            id: 15,
            name: ArmyName::ElvenArchers,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 150,
            attack_speed: 1,
            accuracy: 0.9,
            aoe: 0.00,
            spread: 2.00,
            weapon_type: WeaponType::Piercing,
            armor_type: ArmorType::Leather,
            agility: 0.25,
            speed: 10,
        },
        Army {
            id: 16,
            name: ArmyName::CastlegateCrossbowmen,
            lore: "TBD".to_string(),
            count: 1,
            shield_rating: 0.0,
            flying: false,
            range: 100,
            attack_speed: 2,
            accuracy: 0.85,
            aoe: 0.00,
            spread: 1.00,
            weapon_type: WeaponType::Piercing,
            armor_type: ArmorType::Chain,
            agility: 0.15,
            speed: 5,
        },
    ];
    //vec_of_mock_defaults.sort_by(|a, b| a.id.cmp(&b.id));

    create_hash_of_defaults(vec_of_mock_defaults)
}
